export const ADD_CATEGORY = "add_category"
export const ADD_CATEGORY_DONE = "add_category_done"
export const SET_LEVEL_CATEGORIES = "set_level_categories"
export const DATA_LOADING = "data_loading"
export const DATA_DONE = "data_done"
export const SET_PAGES = "set_pages"
